name: lstn scan

on:
  pull_request:
    branches: ["*"]

jobs:
  lstn:
    name: "lstn scan v2"
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      
      - name: Run lstn scan 
        uses: listendev/action@v0.2.1
        with:
          lstn-flags: "--endpoint=https://npm-staging.listen.dev"
