name: lstn scan

on:
  pull_request:
    branches: ["*"]

permissions:
  contents: read
  pull-requests: write

jobs:
  lstn:
    name: "lstn scan"
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      
      - name: Run lstn scan 
        uses: listendev/action@v0.3.0
