name: lstn scan v1

on:
  pull_request:
    branches: ["*"]

permissions:
  contents: read
  pull-requests: write

jobs:
  lstn:
    name: "lstn dynamic scan"
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      
      - name: Run lstn scan (dynamic)
        uses: listendev/action@scan
        # with:
        #  lstn: "v0.6.0"
