name: lstn scan on pull request

on: 
  pull_request:
    branches: ["*"]

permissions:
  contents: read
  pull-requests: write

jobs:
    lstn-cli-e2e:
      runs-on: ubuntu-latest
      steps:
        - name: Clone repo
          uses: actions/checkout@v3
          with:
            repository: listendev/lstn
            branch: gh-comment-improve
  
        - name: Build lstn CLI from source
          uses: actions/setup-go@v3
          with:
            go-version: '1.19.4'
            cache: true
        - run: |
            go build -o make/make make/main.go
            make/make lstn
            mv lstn /usr/local/bin/ && chmod +x /usr/local/bin/lstn
            lstn version 
  
        - name: Checkout the test repo
          uses: actions/checkout@v3
  
        - name: lstn scan
          run: |
            lstn scan --endpoint https://npm-staging.listen.dev -r gh-pull-comment --gh-owner jadoonf --gh-token ${{ secrets.PERSONAL_ACCESS_TOKEN }} --github-repo ${{ github.repository }} --github-pr ${{ github.event.number }}  lstn:

    # name: Clone repo
    # uses: actions/checkout@v3
    # with:
    #   repository: listendev/lstn
    #   branch: gh-comment-improve

    # - name: Build lstn CLI from source
    #   uses: actions/setup-go@v3
    #   with:
    #     go-version: '1.19.4'
    #     cache: true
    #   run: |
    #     go run make/main.go lstn 
    #     mv ./lstn /usr/local/bin/ && chmod +x /usr/local/bin/lstn
    #     lstn version

    # - name: Scan your dependencies with listen.dev  
    #   run: |
    #     lstn scan --endpoint https://npm-staging.listen.dev -r gh-pull-comment --gh-owner jadoonf --gh-token ${{ secrets.PERSONAL_ACCESS_TOKEN }} --github-repo ${{ github.repository }} --github-pr ${{ github.event.number }}