name: lstn

on:
  pull_request:
    branches: ["*"]

permissions:
  contents: read
  pull-requests: write

jobs:
  lstn:
    name: "lstn dependency scan"
    runs-on: ubuntu-latest

    steps:
      - name: Check out the source code
        uses: actions/checkout@v3
      - uses: listendev/action@v0.2.1
      - uses: listendev/action@v0.2.0
