name: package size check

on:
    pull_request:
      branches: ["*"]
  
  permissions:
    contents: read
    pull-requests: write

jobs:
  pkg-size-report:
    name: Package Size Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' 

      - name: Package size report
        uses: pkg-size/action@v1
